apiVersion: v1
kind: Service
metadata:
  name: greeter-app-service
  namespace: greeter-app
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: greeter-app
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: greeting-message-provider-app-service
  namespace: greeter-app
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: greeting-message-provider-app
  type: LoadBalancer
